'type' => 'group',
'internal_type' => 'file',
'uploadfolder' => '{extension.uploadFolder}',
'show_thumbs' => 1,
'size' => 5,
'allowed' => $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'],
'disallowed' => '{property.disallowedFileTypes}',