base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: us
  -
    title: Dansk
    enabled: true
    languageId: 1
    base: /da/
    typo3Language: da
    locale: da_DK.UTF-8
    iso-639-1: da
    navigationTitle: Dansk
    hreflang: da-DK
    direction: ''
    fallbackType: fallback
    fallbacks: ''
    flag: dk
  -
    title: German
    enabled: true
    languageId: 2
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: fallback
    fallbacks: '1,0'
    flag: de
rootPageId: 1
websiteTitle: 'TYPO3 Introduction Package'
