base: 'https://extensionbuilder.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: en-US
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'ExtensionBuilder Devbox'
