'type' => 'inline',
'size' => 10,
'minitems' => 0,
'maxitems' => 9999,
'autoSizeMax' => 30,
'multiple' => 1,
'foreign_table' => '{property.foreignClass.databaseTableName}',
'MM' => '{property.relationTableName}',