'type' => 'inline',
'size' => 10,
'minitems' => 0,
'maxitems' => 9999,
'autoSizeMax' => 30,
'multiple' => 1,
'foreign_table' => '{property.relationTableName}',
'foreign_field' => 'uid_local',
'foreign_selector' => 'uid_foreign',
'foreign_unique' => 'uid_foreign',
'foreign_sortby' => 'sorting',
'foreign_label' => 'uid_foreign',
'appearance' => array(
	'useCombination' => 1,
	'useSortable' => 1,
	'collapse' => 0,
	'newRecordLinkPosition' => 'bottom',
),