<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "test_extension"
 *
 * Auto generated by Extension Builder 2011-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Compatibility Test Extension Version 1.0',
	'description' => 'This is an extension to the compatibility to future versions of the Extension Builder',
	'category' => 'misc',
	'author' => 'John Doe',
	'author_email' => 'mail@typo3.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);