services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EBT\ExtensionBuilder\:
    resource: '../Classes/*'

  EBT\ExtensionBuilder\Configuration\ExtensionBuilderConfigurationManager:
    public: true

  EBT\ExtensionBuilder\Service\Printer:
    public: true

  EBT\ExtensionBuilder\Command\MigrateExtensionCommand:
    tags:
      - name: 'console.command'
        command: 'extension-builder:migrate-extension'
        description: 'Reads older extensions and rewrite the ExtensionBuilder.json file to match the current TYPO3 version'
        schedulable: false
