name: Label Issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label:
    name: Assign Labels
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Label bug reports"
        if: contains(github.event.issue.body, 'Describe the bug')
        uses: actions/github-script@v9
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['bug']
            });

      - name: "Label feature requests"
        if: contains(github.event.issue.body, 'feature request related to a problem')
        uses: actions/github-script@v9
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['enhancement']
            });
