name: test documentation

on:
  push:
    paths:
      - 'Documentation/**'
      - '.github/workflows/test-documentation.yml'
  pull_request:
    paths:
      - 'Documentation/**'
      - '.github/workflows/test-documentation.yml'

permissions:
  contents: read

jobs:
  tests:
    name: documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Test if the documentation will render without warnings"
        run: |
          mkdir -p Documentation-GENERATED-temp \
          && docker run --rm --pull always -v "$(pwd)":/project \
             ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log
